<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Ngn tnh</name>
   <tag></tag>
   <elementGuidId>6e9f7c0a-6bbc-41c2-8ef7-7082ed52a52d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='mainNav']/div/div/div/div/ul/li[9]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;Truyện tranh ngôn tình&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>13e71e6d-2ea2-40be-bb51-9af26ae7a88e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Truyện tranh ngôn tình</value>
      <webElementGuid>1cb01afa-2f34-49d8-8f1f-a4d8e8410cb1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>dofollow</value>
      <webElementGuid>aa1baa34-c158-4849-b5e6-2f72f7ed021a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>93932741-c5ec-4340-b8f7-4e03e4e6f4d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://nettruyenrr.com/tim-truyen/ngon-tinh</value>
      <webElementGuid>ded1d8c8-f623-41c7-9276-9750f1b5802d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Ngôn tình</value>
      <webElementGuid>a0c6e3ac-7ea6-4ddc-b041-3d542f2d7f28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainNav&quot;)/div[@class=&quot;inner&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;Module Module-144&quot;]/div[@class=&quot;ModuleContent&quot;]/ul[@class=&quot;nav navbar-nav main-menu&quot;]/li[@class=&quot;open&quot;]/a[1]</value>
      <webElementGuid>ace5a176-17b5-4409-8c80-09e5ee9c0ce8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='mainNav']/div/div/div/div/ul/li[9]/a</value>
      <webElementGuid>3128b2a5-bf89-4646-84f7-1850b50ba6a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Ngôn tình')]</value>
      <webElementGuid>3a81fee9-f879-4502-85f4-c35e2d9c16d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manhwa'])[2]/following::a[1]</value>
      <webElementGuid>afce0b5e-0603-4136-b25c-76c9fc021933</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manhua'])[2]/following::a[2]</value>
      <webElementGuid>c942258b-fe87-4c5b-a4d8-12962ffe3cfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Con gái'])[1]/preceding::a[1]</value>
      <webElementGuid>b807ee94-0859-4002-9974-f31fbe7be2f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Con trai'])[1]/preceding::a[2]</value>
      <webElementGuid>161ad87b-b85b-4147-9221-bebeca1f42de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Ngôn tình']/parent::*</value>
      <webElementGuid>e36a49c2-f811-4656-8f99-a389c29678b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://nettruyenrr.com/tim-truyen/ngon-tinh')]</value>
      <webElementGuid>243d415c-4d77-4413-b1b1-8cb3bb019787</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[9]/a</value>
      <webElementGuid>fa7c4a03-a9ae-45c5-9126-fb7a8a5279b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Truyện tranh ngôn tình' and @href = 'https://nettruyenrr.com/tim-truyen/ngon-tinh' and (text() = 'Ngôn tình' or . = 'Ngôn tình')]</value>
      <webElementGuid>47aa7553-f50f-4d33-996b-cde6d586a7a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
