<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_nh ti lu hay li ton b nh_report_er_ea4cb5</name>
   <tag></tag>
   <elementGuidId>1c5d45ad-0ee7-48db-b0c0-86164e7fead5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#report_error_text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='report_error_text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>5f8a8d90-54bb-4384-ad37-df4f0668b86a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>report_error_text</value>
      <webElementGuid>64fe9a64-f4f2-4a49-9342-cfd2e4a50c46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>a721a5a0-bdb8-403b-b91c-a104686c837b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Mô tả...</value>
      <webElementGuid>c4178fc3-4b0f-41d8-ba8f-3e74b4d883dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;report_error_text&quot;)</value>
      <webElementGuid>7ae5e8cb-1a96-4589-b2c2-f6e23a646c61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='report_error_text']</value>
      <webElementGuid>927790c0-db86-407f-8c2e-2df811ccaae3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popup_content']/div/ul/li[2]/textarea</value>
      <webElementGuid>87d8443d-8c56-49e0-b5f4-3b6eaa083a50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>4e6aaa99-1033-4690-be9e-bcbadd5cf8a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'report_error_text' and @placeholder = 'Mô tả...']</value>
      <webElementGuid>d24c51fb-45e2-451b-8ef9-0907708b3ce9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
