<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_S dng mi tn tri () hoc phi ()  chuyn chap_ea74e2</name>
   <tag></tag>
   <elementGuidId>7ede4ebf-b0df-489b-9deb-50c06936fbf2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.next.a_next</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='chapterNav']/a[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7d26c332-673c-4c45-8bef-9732787f2354</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://nettruyenrr.com/truyen-tranh/huyen-tuong-tho-san-tai-di-gioi/chapter-27/29</value>
      <webElementGuid>0902ccab-905c-4d47-88e9-37fdb76f2969</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>next a_next</value>
      <webElementGuid>2a53fa8a-ce34-4960-bb54-332745d59d5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chapterNav&quot;)/a[@class=&quot;next a_next&quot;]</value>
      <webElementGuid>55ff2e2f-305d-4370-bf6f-bcc69c0ba510</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chapterNav']/a[5]</value>
      <webElementGuid>a4e54537-328b-4cb5-a8ca-0f31bea0d82a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sử dụng mũi tên trái (←) hoặc phải (→) để chuyển chapter'])[1]/following::a[5]</value>
      <webElementGuid>58991ebb-14f6-41c8-8165-78fe0d47d912</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Báo lỗi'])[2]/following::a[5]</value>
      <webElementGuid>2290862e-c72d-4b41-a8f7-46270db88d0c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bỏ theo dõi'])[1]/preceding::a[1]</value>
      <webElementGuid>34b8a4ee-d9c4-4413-bf70-ae6841bf3864</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Theo dõi'])[2]/preceding::a[2]</value>
      <webElementGuid>3c64c891-84d7-4fcc-ae0f-8b1f6c0164af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://nettruyenrr.com/truyen-tranh/huyen-tuong-tho-san-tai-di-gioi/chapter-27/29')]</value>
      <webElementGuid>9abca35d-0b59-4b7b-ab1f-7d3ad4822751</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a[5]</value>
      <webElementGuid>85a633df-2467-455f-898d-b30b4a5022a8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://nettruyenrr.com/truyen-tranh/huyen-tuong-tho-san-tai-di-gioi/chapter-27/29']</value>
      <webElementGuid>8f0196ef-c5ca-4b6f-afd4-844783be2ee3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
