<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_X</name>
   <tag></tag>
   <elementGuidId>3cd38d63-ff9d-49e4-839d-ef69f5a3d017</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.wapclosebtn.ads-banner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;jQuery('.wap_bottombanner').fadeOut();&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>a5a4f6f8-e0ff-4d88-a017-cd4c35e9bc5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wapclosebtn ads-banner</value>
      <webElementGuid>bbfd79ac-4a8d-4f94-b263-b69958a886a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>1928a84f-7d38-4f9c-9e4b-200c8e0c0496</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>jQuery('.wap_bottombanner').fadeOut();</value>
      <webElementGuid>077a4df6-f3f6-4fbb-8451-6c432ff01b9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>X</value>
      <webElementGuid>2d145412-7243-43bb-b5d7-141ac6fa8fe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aspnetForm&quot;)/main[@class=&quot;main&quot;]/div[@class=&quot;ads-banner wap_bottombanner banner-desktop&quot;]/div[@class=&quot;wap_bottombanner_content&quot;]/div[@class=&quot;textwidget text-center&quot;]/div[@class=&quot;text-center&quot;]/a[@class=&quot;wapclosebtn ads-banner&quot;]</value>
      <webElementGuid>7bba992f-96c4-4ec2-9fbc-103234917087</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;jQuery('.wap_bottombanner').fadeOut();&quot;]</value>
      <webElementGuid>28d64d3f-21df-4855-9547-3da3bd0445d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='aspnetForm']/main/div[2]/div/div/div/a</value>
      <webElementGuid>90ec6074-3258-4471-8077-429f0ccbfe11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'X')])[2]</value>
      <webElementGuid>ddf1fc2f-ec08-4436-a908-3bf3a6bf38ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='nettruyenrr.com'])[1]/following::a[13]</value>
      <webElementGuid>fd99ab0a-0d70-4d94-8a26-2506e0bfa4f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Con trai'])[1]/following::a[13]</value>
      <webElementGuid>14232286-1707-4800-a268-011c90fe44ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='X'])[2]/preceding::a[5]</value>
      <webElementGuid>372d50df-ed2c-42ab-8d19-3e4a61e862cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='X'])[3]/preceding::a[14]</value>
      <webElementGuid>3f141001-1fa5-4749-82e6-05f9188bb1a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='X']/parent::*</value>
      <webElementGuid>4054862c-0ac6-4130-b55f-ecb5f07d9125</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:;')]</value>
      <webElementGuid>8c2db442-b0d4-4f79-873b-c26cd0e2ec95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/a</value>
      <webElementGuid>014b08fd-dc0b-413e-85bc-af76655d643d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and (text() = 'X' or . = 'X')]</value>
      <webElementGuid>f2b1e83c-cedf-42f0-a8e5-2d461dfb4583</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
