<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_im danh</name>
   <tag></tag>
   <elementGuidId>8d782ab8-a752-4aad-9585-13d3884b28bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#diemDanhBtn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='diemDanhBtn']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cd412211-cffd-4458-9300-9ff39ec95cfe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-success</value>
      <webElementGuid>36b3e92e-733f-4c1e-965c-a9fed3bcb5c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>diemDanhBtn</value>
      <webElementGuid>2f6c368c-d8fd-486b-81e6-6b3a24e38014</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ca06d7ae-ebc9-4ab2-a27b-c3cbb4d52358</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>diemdanh()</value>
      <webElementGuid>e3bd3745-a35f-49c3-90d2-1bfa557805f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Điểm danh </value>
      <webElementGuid>49c9e56b-f699-4ff1-a481-02292805e7e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;diemDanhBtn&quot;)</value>
      <webElementGuid>bfec43e5-321d-4365-b6c6-8fcd38fa0eb3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='diemDanhBtn']</value>
      <webElementGuid>64dbe68b-e230-47bb-980c-08104615c879</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='diemDanh']/button</value>
      <webElementGuid>c31c27a9-ba04-4ac0-a861-d084f13a4baf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Điểm danh liên tục 7 ngày sẽ tặng thêm 300 Linh thạch'])[1]/following::button[1]</value>
      <webElementGuid>4034d3cb-ff38-43a9-8e6f-1b0b044e68b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mỗi lần điểm danh sẽ nhận được 100 Linh thạch'])[1]/following::button[1]</value>
      <webElementGuid>171c722e-5491-4f71-a225-81c22746e888</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lưu ý'])[2]/preceding::button[1]</value>
      <webElementGuid>0efa3cf2-e60d-4df1-8d1e-a5ea377b9bd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button</value>
      <webElementGuid>e73364cf-ada9-4c24-87a5-1462e505f00f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'diemDanhBtn' and @type = 'button' and (text() = ' Điểm danh ' or . = ' Điểm danh ')]</value>
      <webElementGuid>4b64e0c4-a6e3-49b8-94dc-ac2919b09dd5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
