<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Quay</name>
   <tag></tag>
   <elementGuidId>18c45a26-fef3-4b43-8698-d0276b09fbff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button.btn-spin</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='nt_luckyDraw']/div/div/button</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>cd1e9656-e1bf-4173-9a1b-eb96f05f4e9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn-spin</value>
      <webElementGuid>c63f4500-c1d8-4e3d-91d6-08115142b810</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Quay</value>
      <webElementGuid>4686a1e0-a823-4dc1-a548-d32fa5ee83f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nt_luckyDraw&quot;)/div[@class=&quot;deal-container&quot;]/div[@class=&quot;deal-wheel&quot;]/button[@class=&quot;btn-spin&quot;]</value>
      <webElementGuid>33aee119-2101-4d6e-9c9c-9d8353e91211</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='nt_luckyDraw']/div/div/button</value>
      <webElementGuid>2d62f948-d8cf-4b41-9151-4d2101d534b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mất lượt'])[2]/following::button[1]</value>
      <webElementGuid>1a20a60d-8a2e-45e3-837e-ee7ed8f5787a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thêm lượt'])[2]/following::button[1]</value>
      <webElementGuid>794014bb-2fba-45aa-92ac-c33cecdb7350</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tính năng đang thực hiện'])[1]/preceding::button[1]</value>
      <webElementGuid>dd40c2f3-0690-4f74-b893-05c2db38bc6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Giới thiệu'])[1]/preceding::button[1]</value>
      <webElementGuid>3c004301-15cb-4866-94b1-23d21e04d561</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Quay']/parent::*</value>
      <webElementGuid>de80ffdb-3424-4003-8b5e-7ccdcd2ce7c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/button</value>
      <webElementGuid>940c34f6-aa5d-49e2-a92a-7a9dd61ea2a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = 'Quay' or . = 'Quay')]</value>
      <webElementGuid>f041cdf4-bf1e-4e50-a6fa-311c7a19f60f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
