<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ng nhp_ctl00_mainContent_login1_Login_ad5eda</name>
   <tag></tag>
   <elementGuidId>ceed9262-6381-407a-8769-19b6df37f6ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_mainContent_login1_LoginCtrl_Login']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_mainContent_login1_LoginCtrl_Login</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>58814d26-cdc1-4b88-9fce-fa82273627e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>b7744685-962e-4b9e-8986-9897fb535ac1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Đăng ký</value>
      <webElementGuid>030f2554-9f4b-4b79-8395-1772e8e6809c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_mainContent_login1_LoginCtrl_Login</value>
      <webElementGuid>c08ca41f-4c95-4e61-b585-c3a39fe0c4ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>5199a638-fa8b-4929-bdb6-d262ce751ef7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>84c31656-5849-4faf-9815-8f8b82470d54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_mainContent_login1_LoginCtrl_Login&quot;)</value>
      <webElementGuid>23647a44-b402-4d1b-872d-43c5848060a7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_mainContent_login1_LoginCtrl_Login']</value>
      <webElementGuid>5c50a52d-3119-486c-8a28-2eb3d1506989</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_divCenter']/div/div/div/div[2]/div[2]/input</value>
      <webElementGuid>33553fee-8bf0-4cbf-95a1-3a54dc3d96dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>3f16eb68-90af-4cd7-93f7-22d89c5eebfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'ctl00_mainContent_login1_LoginCtrl_Login']</value>
      <webElementGuid>ffbf2889-e0c7-4f3d-85b8-137bf6e2c441</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
