<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_ng k_ctl00_mainContent_login1_LoginCt_5c7369</name>
   <tag></tag>
   <elementGuidId>3ec95dd3-0272-4f16-a2f7-5a94eeeb6d7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ctl00_mainContent_login1_LoginCtrl_Login']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ctl00_mainContent_login1_LoginCtrl_Login</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>286e9d4b-3410-4e21-ae5b-86baaff39aba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>f9d3e62c-eb66-45ef-b183-d50e26ffd39a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Đăng nhập</value>
      <webElementGuid>0e1c810f-1ee9-4011-ac38-facfd7fd6116</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ctl00_mainContent_login1_LoginCtrl_Login</value>
      <webElementGuid>65e16954-a30c-4327-ab3a-9fe75ea662fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>10</value>
      <webElementGuid>61c73b73-26e4-47fe-b330-f42d57df4ee0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary</value>
      <webElementGuid>270438d1-0618-48e6-b6c6-f350400816b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_mainContent_login1_LoginCtrl_Login&quot;)</value>
      <webElementGuid>acbfbfad-54bf-433a-909b-78b0b4d3ce30</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ctl00_mainContent_login1_LoginCtrl_Login']</value>
      <webElementGuid>0705c011-f56b-4fb5-97ef-bdf0505bc135</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_mainContent_pnlStandardLogin']/div/div/div/div[2]/div[2]/input</value>
      <webElementGuid>785d35ad-c481-4e89-9d47-980a617a05bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/input</value>
      <webElementGuid>5f2ccd67-145d-41fb-bd82-fcb627c5cf64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @id = 'ctl00_mainContent_login1_LoginCtrl_Login']</value>
      <webElementGuid>86cd50de-a2b3-4b8e-989b-1c3720832286</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
