<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_</name>
   <tag></tag>
   <elementGuidId>1a8d2ffd-fff1-4915-876c-482997aa8c2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#close-_pop-nettruyenrr-21</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='close-_pop-nettruyenrr-21']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>be096311-4425-4fa8-b5ab-c07ab3c13fc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ads-banner</value>
      <webElementGuid>8d923fad-0008-4b6a-bab6-4a0a79f0b06b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>close-_pop-nettruyenrr-21</value>
      <webElementGuid>ec3f55de-af35-4253-bf34-556983706de6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×</value>
      <webElementGuid>3f6bf639-3df5-490a-a8eb-e0a388906fd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;close-_pop-nettruyenrr-21&quot;)</value>
      <webElementGuid>df220402-7ffc-454f-aa27-e4f80b62cf2d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='close-_pop-nettruyenrr-21']</value>
      <webElementGuid>1a63ac57-f8e6-4931-bff4-fcfdbca12340</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_pop-nettruyenrr-21']/div/div/div/div</value>
      <webElementGuid>e196bb53-8e40-4a19-b3e1-83e9aa83d44c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[2]/following::div[5]</value>
      <webElementGuid>7b206f7e-6832-49c6-bddf-53a8f3e280fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[4]/preceding::div[1]</value>
      <webElementGuid>70c39eab-5b2f-4afb-aa89-4ea70cff2450</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[5]/preceding::div[6]</value>
      <webElementGuid>ebcb9de0-ea89-4078-9253-5a35cbf8f10f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div</value>
      <webElementGuid>4fb993a4-3129-419d-a31d-327214c138f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'close-_pop-nettruyenrr-21' and (text() = '×' or . = '×')]</value>
      <webElementGuid>7ed4095a-ca81-4c90-aac4-9737bffaaf8c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
