<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_X</name>
   <tag></tag>
   <elementGuidId>db202f8a-1c46-4b28-bef1-c6a05bbc79a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.wapclosebtn.ads-banner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;jQuery('.wap_bottombanner').fadeOut();&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5000143f-4fe1-4bbc-b283-076338335a02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wapclosebtn ads-banner</value>
      <webElementGuid>164bb72f-5463-4ca3-a049-c423cb53e167</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>1aa6e652-0ca8-437c-8271-0977e2aaaef4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>jQuery('.wap_bottombanner').fadeOut();</value>
      <webElementGuid>94470f8d-c7e5-4bf6-a642-954c8dc155d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>X</value>
      <webElementGuid>a0ed2253-2f84-44a2-af5a-e42110cfecde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aspnetForm&quot;)/main[@class=&quot;main&quot;]/div[@class=&quot;ads-banner wap_bottombanner banner-desktop&quot;]/div[@class=&quot;wap_bottombanner_content&quot;]/div[@class=&quot;textwidget text-center&quot;]/div[@class=&quot;text-center&quot;]/a[@class=&quot;wapclosebtn ads-banner&quot;]</value>
      <webElementGuid>80bf449e-655f-4f28-9319-7cabf1cd6ec6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;jQuery('.wap_bottombanner').fadeOut();&quot;]</value>
      <webElementGuid>ff745258-4352-4e8f-abe1-83ad4904bd8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='aspnetForm']/main/div[2]/div/div/div/a</value>
      <webElementGuid>30b19847-f2d6-4c6c-9d74-35aaf0575659</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'X')])[2]</value>
      <webElementGuid>72471e2f-b0fa-4c82-8966-700d89b3cfda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='nettruyenrr.com'])[1]/following::a[13]</value>
      <webElementGuid>f5fcaa6b-84d3-446d-8950-4a7ff67f3b21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Con trai'])[1]/following::a[13]</value>
      <webElementGuid>4eeaabc9-304a-42ee-914f-5173c7780d20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='X'])[2]/preceding::a[5]</value>
      <webElementGuid>a793ec28-0f6f-4bc2-8a14-c00c421124b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='X'])[3]/preceding::a[14]</value>
      <webElementGuid>0488cc60-0398-4ad1-ae3e-fa8cbc1a49f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='X']/parent::*</value>
      <webElementGuid>9813345a-4158-4c2a-99f7-7d966d49f8e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:;')]</value>
      <webElementGuid>ec39395d-26da-4bbf-b191-35ef2d36a906</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/a</value>
      <webElementGuid>9e3c4a7f-6a55-4e7f-b2f3-64e42adadf53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and (text() = 'X' or . = 'X')]</value>
      <webElementGuid>4c78e136-ac46-4455-ad6f-c85ba8690df7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
