<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_S dng mi tn tri () hoc phi ()  chuyn chap_ee3f92</name>
   <tag></tag>
   <elementGuidId>9a4cfd81-fdf1-42a7-a98e-58c95bcf97e4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.home > i.fa.fa-home</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='chapterNav']/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>ed828817-c573-427a-ac98-89db61fed932</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-home</value>
      <webElementGuid>7750ce35-efce-4b29-9c9b-da0334944e76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chapterNav&quot;)/a[@class=&quot;home&quot;]/i[@class=&quot;fa fa-home&quot;]</value>
      <webElementGuid>65f2ec16-41ca-4ebd-ab37-382db74ad853</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chapterNav']/a/i</value>
      <webElementGuid>2f35a865-e093-4c47-8379-3997e2fe181e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a/i</value>
      <webElementGuid>ae5d60a5-6260-446a-8f9a-4474b83d4c02</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
