<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Bo li</name>
   <tag></tag>
   <elementGuidId>23094ab3-2563-4f34-9c18-9fab007b6ca5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.alertError.btn.btn-warning</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/span/span/span/ul/li[4]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>441256db-ff2e-4b90-948c-d6388a74f58d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>nofollow</value>
      <webElementGuid>5aba60b3-cbe2-4906-835f-8626eabbf78d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0)</value>
      <webElementGuid>dff427bb-fbad-479b-95ff-405929a6236f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>alertError btn btn-warning</value>
      <webElementGuid>dccfa2e1-a41f-43a4-94a8-e15aa176795a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Báo lỗi</value>
      <webElementGuid>d51c41ea-fe2e-40eb-8be3-02555fd1e095</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_divCenter&quot;)/div[@class=&quot;reading&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;reading-control&quot;]/div[@class=&quot;mrb10&quot;]/a[@class=&quot;alertError btn btn-warning&quot;]</value>
      <webElementGuid>446a61b4-6c9d-497d-8f6d-9cd841e027d0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_divCenter']/div/div/div[2]/div[2]/a</value>
      <webElementGuid>f55202af-3aab-4162-9a5c-6a9a90de7225</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Báo lỗi')]</value>
      <webElementGuid>77812ae0-254a-4a35-852d-fb7c9ffb5fa5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Server 2'])[1]/following::a[1]</value>
      <webElementGuid>7740128d-db6d-41b9-a38b-6a2c7bb42395</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Server 1'])[1]/following::a[2]</value>
      <webElementGuid>74453608-e102-4ceb-bd63-2c1184facc6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sử dụng mũi tên trái (←) hoặc phải (→) để chuyển chapter'])[1]/preceding::a[1]</value>
      <webElementGuid>a061b7be-f6e6-4b5c-95ba-43d174dab515</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bỏ theo dõi'])[1]/preceding::a[6]</value>
      <webElementGuid>2c4c8f05-16e8-46e1-abe1-492aad6cc283</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0)')])[2]</value>
      <webElementGuid>7931ddad-ee4b-42ec-afe3-d6a1be0203e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div[2]/a</value>
      <webElementGuid>601392d4-93a7-4db7-9bae-ca31879f8cfe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:void(0)' and (text() = ' Báo lỗi' or . = ' Báo lỗi')]</value>
      <webElementGuid>a70abb37-db50-49f8-8da2-c1e5925f7047</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
