<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_X</name>
   <tag></tag>
   <elementGuidId>939360bf-1e89-4c89-8c78-99bfa6af3193</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.wapclosebtn.ads-banner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;jQuery('.wap_bottombanner').fadeOut();&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>5bc454eb-a8a4-48a3-846a-7148cdf3e5ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wapclosebtn ads-banner</value>
      <webElementGuid>fa98fea7-9934-4fc6-b465-b8bfea32c0ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>ffa3b593-33a0-43cb-8d60-0c9142f1df28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>jQuery('.wap_bottombanner').fadeOut();</value>
      <webElementGuid>e0a3fd0a-8c35-4dd2-a489-b53b5831336f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>X</value>
      <webElementGuid>39f1aa53-1af5-4c3d-afe9-dfcc7d22408e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aspnetForm&quot;)/main[@class=&quot;main&quot;]/div[@class=&quot;ads-banner wap_bottombanner banner-desktop&quot;]/div[@class=&quot;wap_bottombanner_content&quot;]/div[@class=&quot;textwidget text-center&quot;]/div[@class=&quot;text-center&quot;]/a[@class=&quot;wapclosebtn ads-banner&quot;]</value>
      <webElementGuid>d30dbc4f-41ea-4932-8c18-9feb1ecbc726</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;jQuery('.wap_bottombanner').fadeOut();&quot;]</value>
      <webElementGuid>96eee6e1-126b-4920-8d45-1e760018294c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='aspnetForm']/main/div[2]/div/div/div/a</value>
      <webElementGuid>58c879a3-2394-4323-86ad-c900161c750c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'X')])[2]</value>
      <webElementGuid>8d07b9b1-5be8-4b0b-816d-05f34d2a9eec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='nettruyenrr.com'])[1]/following::a[13]</value>
      <webElementGuid>1dd1f79e-95ec-4560-b41c-ab8336dfa42b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Con trai'])[1]/following::a[13]</value>
      <webElementGuid>dfa2f6e9-1bf7-425b-825b-961105240c19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='X'])[2]/preceding::a[5]</value>
      <webElementGuid>4dccab73-b393-4267-a3b2-164d590c68df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='X'])[3]/preceding::a[14]</value>
      <webElementGuid>a5f32ef8-4d18-459b-a643-4bd1fe3cf6cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='X']/parent::*</value>
      <webElementGuid>d30d66bc-8d70-4631-9bbd-eb0f8eb38128</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:;')]</value>
      <webElementGuid>9ccfa58c-d408-431d-b95b-291391423834</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/a</value>
      <webElementGuid>07d989cb-29de-40c0-a1c6-b7fe15d92f1a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and (text() = 'X' or . = 'X')]</value>
      <webElementGuid>0fb1b553-2fa4-4810-bf66-4d96c58053e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
