<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_--Chn loi li--   nh li, khng thy nh _96f8c9</name>
   <tag></tag>
   <elementGuidId>527ad4ba-af77-422b-a7df-575978376d8e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#report_error_title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='report_error_title']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>17a1672d-e8d9-4a44-bc2a-ac90bd10b60f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>report_error_title</value>
      <webElementGuid>0029282c-7c32-4d31-a12d-19ab0c72d002</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>$('.note').text($(this).children('option:selected').attr('note')); $('.empty_error').css('display', 'none');</value>
      <webElementGuid>74b2a29c-e771-40c2-9681-9aaff3c4602d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  --Chọn loại lỗi--   Ảnh lỗi, không thấy ảnh   Chapter bị trùng   Chapter chưa dịch   Up sai truyện   Truyện 18+   Lỗi khác   </value>
      <webElementGuid>e8c3ba64-970e-4ec1-ab55-7f3dd20ceaca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;report_error_title&quot;)</value>
      <webElementGuid>9f516893-e337-496c-b314-a1f07f59ec01</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='report_error_title']</value>
      <webElementGuid>89945335-1a0a-491e-b37d-0340a1af8f2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popup_content']/div/ul/li/select</value>
      <webElementGuid>a4c0f9f7-1889-4ed3-90c7-2025a3b5028a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Báo lỗi'])[1]/following::select[1]</value>
      <webElementGuid>6a9bb0e0-0865-4040-914c-39b504c0752a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='X'])[3]/following::select[1]</value>
      <webElementGuid>b775a4aa-93bf-4ffd-91f9-cd77d92626af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Vui lòng chọn loại lỗi !'])[1]/preceding::select[1]</value>
      <webElementGuid>6bf8d1dc-484c-43b5-a53c-cdf139682e85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mô tả chi tiết lỗi để được ưu tiên fix sớm nhất.'])[1]/preceding::select[1]</value>
      <webElementGuid>c45d1ab0-1b0c-4688-83a7-c07fc45eb29e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>078828ac-0e7e-4149-89e1-6232034ea27d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'report_error_title' and (text() = '  --Chọn loại lỗi--   Ảnh lỗi, không thấy ảnh   Chapter bị trùng   Chapter chưa dịch   Up sai truyện   Truyện 18+   Lỗi khác   ' or . = '  --Chọn loại lỗi--   Ảnh lỗi, không thấy ảnh   Chapter bị trùng   Chapter chưa dịch   Up sai truyện   Truyện 18+   Lỗi khác   ')]</value>
      <webElementGuid>7bdfde0c-1d89-4b6b-b5bd-7050f20497f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
