<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Chapter khng phi truyn ny_report_e_b81a5e</name>
   <tag></tag>
   <elementGuidId>e9420606-4b0c-4bc8-a7d6-8a659225c657</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#report_error_text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='report_error_text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>5c264ac2-52c3-40a2-9d83-f4590c8b6787</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>report_error_text</value>
      <webElementGuid>aaf862a7-fc5d-460c-acab-6205c8167eb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>d835a992-4bf4-48a0-9886-a903c168dd8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Mô tả...</value>
      <webElementGuid>d923b058-9892-4575-a737-efaae31fc87b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;report_error_text&quot;)</value>
      <webElementGuid>5296045c-94a2-4f53-b232-e6c8ff853561</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='report_error_text']</value>
      <webElementGuid>8cd7cd0a-88b8-4caf-a9c8-455661c1efee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popup_content']/div/ul/li[2]/textarea</value>
      <webElementGuid>f3e2de19-e534-4502-a9a3-02cdcf381e80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>f707e01a-5be7-4ed4-808f-c4654dc53ff7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'report_error_text' and @placeholder = 'Mô tả...']</value>
      <webElementGuid>589515c1-1fa9-4025-9dac-fba30f636185</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
