<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_</name>
   <tag></tag>
   <elementGuidId>0c8f4e1b-ad55-4c57-9bc3-03d65fcff105</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#close-_pop-nettruyenrr-18</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='close-_pop-nettruyenrr-18']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>65d9d6e9-946a-43fc-a167-19fdb6043a2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ads-banner</value>
      <webElementGuid>e2b3a588-354a-419a-a76f-fd04957d8a57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>close-_pop-nettruyenrr-18</value>
      <webElementGuid>1fafef4e-be1a-402a-a884-58020a07dfdd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×</value>
      <webElementGuid>b6381d3a-9966-44f5-83c2-b535d6224fed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;close-_pop-nettruyenrr-18&quot;)</value>
      <webElementGuid>1defc99d-7197-43f4-9f8d-09f151535faa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='close-_pop-nettruyenrr-18']</value>
      <webElementGuid>7a9397f7-2eb4-41c7-a214-905b0ce96f5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_pop-nettruyenrr-18']/div/div/div/div</value>
      <webElementGuid>605bba78-3867-408a-ae90-42f7558e6b2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thoát'])[2]/following::div[5]</value>
      <webElementGuid>06d9be2a-e169-43f1-aa4e-0882b014741b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[3]/preceding::div[1]</value>
      <webElementGuid>a5b38de8-ecf4-43c0-951f-1e1c19d03f99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[4]/preceding::div[6]</value>
      <webElementGuid>ff514f55-9496-47e0-b2ed-5060f18b44fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/div/div/div/div/div</value>
      <webElementGuid>70db1cc9-0f6f-47c8-8998-68d0a4fa0802</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'close-_pop-nettruyenrr-18' and (text() = '×' or . = '×')]</value>
      <webElementGuid>7e32d5de-5919-4fa9-969f-460cd3f4bfa1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
