<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_X</name>
   <tag></tag>
   <elementGuidId>8f70194a-938c-4e6a-96ac-499491ceecab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.wapclosebtn.ads-banner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;jQuery('.wap_bottombanner').fadeOut();&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>823e6ea4-59f0-4f68-8fa4-7bc34667e1a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wapclosebtn ads-banner</value>
      <webElementGuid>6467e061-5cea-4de7-9bdf-5b70e9e73c49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>9784423f-91ae-4746-b080-c790b2ef6c09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>jQuery('.wap_bottombanner').fadeOut();</value>
      <webElementGuid>46c9599a-a466-4885-a9f7-52076ae559c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>X</value>
      <webElementGuid>12595c40-c114-4b5b-a0c2-bff71f1e62ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aspnetForm&quot;)/main[@class=&quot;main&quot;]/div[@class=&quot;ads-banner wap_bottombanner banner-desktop&quot;]/div[@class=&quot;wap_bottombanner_content&quot;]/div[@class=&quot;textwidget text-center&quot;]/div[@class=&quot;text-center&quot;]/a[@class=&quot;wapclosebtn ads-banner&quot;]</value>
      <webElementGuid>c33033aa-029e-4230-a30b-9b595a3505de</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;jQuery('.wap_bottombanner').fadeOut();&quot;]</value>
      <webElementGuid>5cfe5dc7-00d6-4002-b0a9-a3bce8b6ee96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='aspnetForm']/main/div[2]/div/div/div/a</value>
      <webElementGuid>d9b5ee63-9e7a-4f04-acfb-5e71d14a8f08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'X')])[2]</value>
      <webElementGuid>f5025d39-1bfc-4a4f-97d8-318fe440484a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='nettruyenrr.com'])[1]/following::a[13]</value>
      <webElementGuid>c3edb2c6-3e67-4aed-abe3-250f91e4c9c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Con trai'])[1]/following::a[13]</value>
      <webElementGuid>38162fd6-eee1-46a7-90e0-6454bc801f9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='X'])[2]/preceding::a[5]</value>
      <webElementGuid>0609884b-a9c7-449e-bfce-56128427338b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='X'])[3]/preceding::a[14]</value>
      <webElementGuid>93790171-cf04-4696-b8d5-8a4b6dffbb29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='X']/parent::*</value>
      <webElementGuid>921fb17f-8216-4d1f-9eeb-6dd9cc84465f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:;')]</value>
      <webElementGuid>319365e8-0a54-4dcd-94d8-679dce45ff56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/a</value>
      <webElementGuid>25fbd5e9-5536-4386-8a16-980dfb0d8215</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and (text() = 'X' or . = 'X')]</value>
      <webElementGuid>d46e360b-ee0c-4a01-afa4-d0e2a782d439</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
