<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_S dng mi tn tri () hoc phi ()  chuyn chap_83e6d8</name>
   <tag></tag>
   <elementGuidId>7e55188c-b456-4b48-98a6-39496d5190f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-chevron-left</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='chapterNav']/a[4]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>37a51a3b-b339-40bb-917b-ec5f841ff279</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-chevron-left</value>
      <webElementGuid>dc71635f-9e29-4587-bec1-80e715cf8313</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chapterNav&quot;)/a[@class=&quot;prev a_prev&quot;]/i[@class=&quot;fa fa-chevron-left&quot;]</value>
      <webElementGuid>f8e02772-605f-4cad-a328-c363faa583f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chapterNav']/a[4]/i</value>
      <webElementGuid>8f2c63ec-2765-41b7-b44f-d46b9366b9de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[4]/i</value>
      <webElementGuid>58d15e32-753d-4501-b773-6a3ce0562409</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
