<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_S dng mi tn tri () hoc phi ()  chuyn chap_ee3f92</name>
   <tag></tag>
   <elementGuidId>1e4d62b6-41a6-42d4-83bf-da9590be8680</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.home > i.fa.fa-home</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='chapterNav']/a/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>a4ab7453-493c-4a96-9215-d8af9ae7e00f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-home</value>
      <webElementGuid>2ac87a5f-2965-41dc-ac60-9207e2544ce6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chapterNav&quot;)/a[@class=&quot;home&quot;]/i[@class=&quot;fa fa-home&quot;]</value>
      <webElementGuid>75719bc9-b921-4217-88de-859f7fba7d53</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chapterNav']/a/i</value>
      <webElementGuid>71b91e26-b238-4eb5-96e8-41901668fd96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a/i</value>
      <webElementGuid>bef54ba0-7491-4954-a2bd-6ace647641dc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
