<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Chapter 50_lazy image-thumb</name>
   <tag></tag>
   <elementGuidId>c8d5c395-e177-4650-ba1a-cbc26b8e29f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ctl00_divAlt1']/div/div/div/div/div/div/div[3]/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>9390dd4d-74bf-41f3-99cb-0bd0be5674ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lazy image-thumb</value>
      <webElementGuid>b10a251f-89c3-4928-8738-a672c58eb264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onerror</name>
      <type>Main</type>
      <value>handleImageError(this)</value>
      <webElementGuid>daa6a902-17e6-4566-8046-fe95795f82b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdn1.cloud-zzz.com/nettruyen/thumb/su-tro-lai-cua-anh-hung-diet-the.jpg</value>
      <webElementGuid>01941835-e58e-44e7-afce-3c45c7485f42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-retries</name>
      <type>Main</type>
      <value>https://cdn1.cloud-ccc.com/nettruyen/thumb/su-tro-lai-cua-anh-hung-diet-the.jpg</value>
      <webElementGuid>5ec6f533-ff14-4526-b8be-ebd27e212af1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original</name>
      <type>Main</type>
      <value>https://cdn1.cloud-zzz.com/nettruyen/thumb/su-tro-lai-cua-anh-hung-diet-the.jpg</value>
      <webElementGuid>ceaa42f9-c6d4-44ac-8abb-e0d569ba1a46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Sự Trở Lại Của Anh Hùng Diệt Thế</value>
      <webElementGuid>1d148460-2e52-47d3-9061-4294dd1f9655</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>referrerpolicy</name>
      <type>Main</type>
      <value>origin</value>
      <webElementGuid>3f3b9ba8-53bb-4c55-af46-196fa3191a98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_divAlt1&quot;)/div[@class=&quot;top-comics Module Module-183&quot;]/div[@class=&quot;ModuleContent&quot;]/div[@class=&quot;items-slide&quot;]/div[@class=&quot;owl-carousel clearfix owl-theme&quot;]/div[@class=&quot;owl-wrapper-outer&quot;]/div[@class=&quot;owl-wrapper&quot;]/div[@class=&quot;owl-item&quot;]/div[@class=&quot;item&quot;]/a[1]/img[@class=&quot;lazy image-thumb&quot;]</value>
      <webElementGuid>7ba6ec9a-98f9-49a7-ac92-86a1e5f0740c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_divAlt1']/div/div/div/div/div/div/div[3]/div/a/img</value>
      <webElementGuid>01f8889e-a100-4737-8d57-02ec2ed78e6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Sự Trở Lại Của Anh Hùng Diệt Thế']</value>
      <webElementGuid>0202e315-67fc-426c-8669-e654b85ec261</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/a/img</value>
      <webElementGuid>479f1744-df35-4733-8332-e4cd7af4800e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://cdn1.cloud-zzz.com/nettruyen/thumb/su-tro-lai-cua-anh-hung-diet-the.jpg' and @alt = 'Sự Trở Lại Của Anh Hùng Diệt Thế']</value>
      <webElementGuid>1ba8286b-3c1f-426a-a06a-94f2cc2fcb16</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
