<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Hon thnh</name>
   <tag></tag>
   <elementGuidId>89b65d6d-ed43-4af6-afb0-d369b648c19d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_mainContent_ctl00_ulStatus > li:nth-of-type(2) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='ctl00_mainContent_ctl00_ulStatus']/li[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2d5b7a3e-e615-43a6-b28b-031f95ae7e2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>?status=2&amp;sort=</value>
      <webElementGuid>4ab460ef-435e-43de-9b16-9de81065cdca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Hoàn thành</value>
      <webElementGuid>fb8484db-7f37-445a-a76e-1fc173f02c18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_mainContent_ctl00_ulStatus&quot;)/li[2]/a[1]</value>
      <webElementGuid>63f46b34-10f6-49ca-9b3e-71efb63f4a24</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ctl00_mainContent_ctl00_ulStatus']/li[2]/a</value>
      <webElementGuid>b2726cae-b3ec-45e6-8c1e-95689af52026</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Hoàn thành')]</value>
      <webElementGuid>3631bb71-e726-4428-9e0f-a1cb799985c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tất cả'])[3]/following::a[1]</value>
      <webElementGuid>4f9d9ba0-104b-4caf-a240-d22c33671b87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Top Truyện Tranh Action | Đọc Truyện Tranh Action Full | NetTruyen'])[2]/following::a[2]</value>
      <webElementGuid>385482ee-8a24-4527-bdcd-a4d211f2bc7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đang tiến hành'])[1]/preceding::a[1]</value>
      <webElementGuid>e47af807-115e-4a6a-87b6-ab4da7cc596b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sắp xếp theo:'])[1]/preceding::a[2]</value>
      <webElementGuid>b10aa608-b787-4203-a866-b154131b8d10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Hoàn thành']/parent::*</value>
      <webElementGuid>5a7721c2-e0fb-4b7d-88f1-921812d02376</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '?status=2&amp;sort=')]</value>
      <webElementGuid>d67001a0-a219-4308-b388-8ec642f774f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/ul/li[2]/a</value>
      <webElementGuid>1865ff6b-54ef-496d-84a4-ccadd7ba0776</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '?status=2&amp;sort=' and (text() = 'Hoàn thành' or . = 'Hoàn thành')]</value>
      <webElementGuid>2ec511db-d2af-4d3f-9b26-a39088b78f51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
