<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_S chapter_fa fa-list</name>
   <tag></tag>
   <elementGuidId>f668cd80-610c-40ac-b136-1b85ec07b008</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>i.fa.fa-list</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ctl00_mainContent_ctl00_divSort']/div[2]/div/a[9]/i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>5a87ea79-2fb0-4474-bb26-b4cd7d7ff2b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-list</value>
      <webElementGuid>27cc4763-ff2f-49f2-9623-bcc8260da3c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_mainContent_ctl00_divSort&quot;)/div[@class=&quot;col-sm-9&quot;]/div[@class=&quot;hidden-xs&quot;]/a[9]/i[@class=&quot;fa fa-list&quot;]</value>
      <webElementGuid>dbdfc79f-3ae3-4890-a658-8235a9e289db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_mainContent_ctl00_divSort']/div[2]/div/a[9]/i</value>
      <webElementGuid>4a324cc4-2ee0-4cd4-95b0-161a8157cc5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[9]/i</value>
      <webElementGuid>1dd15027-d163-4e98-bea8-8ab75e77bf4d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
