<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Con gi</name>
   <tag></tag>
   <elementGuidId>bf57fd62-67f5-4b12-b03f-3cf4a738ac66</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li.open > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//nav[@id='mainNav']/div/div/div/div/ul/li[10]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>254351b4-777c-46ff-b93e-d4b4f63e2854</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>nofollow</value>
      <webElementGuid>6dcc8001-99f8-4dad-b76a-7073151ea8e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_self</value>
      <webElementGuid>3f33f89b-3491-4e02-b0af-eedff990eaf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/truyen-tranh-con-gai</value>
      <webElementGuid>403bd640-eceb-4433-815a-7dba8d87d941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Con gái</value>
      <webElementGuid>97ccc9a8-92a0-469f-be20-4f3359406d9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;mainNav&quot;)/div[@class=&quot;inner&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;Module Module-144&quot;]/div[@class=&quot;ModuleContent&quot;]/ul[@class=&quot;nav navbar-nav main-menu&quot;]/li[@class=&quot;open&quot;]/a[1]</value>
      <webElementGuid>b9913b10-a2a4-466a-8dfe-0041a2c4f066</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//nav[@id='mainNav']/div/div/div/div/ul/li[10]/a</value>
      <webElementGuid>d3e6115a-e8a0-4324-9b0f-acf51563e0a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Con gái')]</value>
      <webElementGuid>4a0af67a-5f3b-4427-828b-4409b4ab778c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ngôn tình'])[1]/following::a[1]</value>
      <webElementGuid>18162766-31ea-4d1f-bd94-3089a0ef964f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manhwa'])[2]/following::a[2]</value>
      <webElementGuid>f1698593-a3e1-4142-8ad8-740800767249</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Con trai'])[1]/preceding::a[1]</value>
      <webElementGuid>9fb35ecb-b2ea-4c1e-9d44-40c64a155af9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='nettruyenrr.com'])[1]/preceding::a[2]</value>
      <webElementGuid>7cbe903b-7cb6-45d1-8c33-cff1f94c9c85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Con gái']/parent::*</value>
      <webElementGuid>14612123-be31-43e5-b029-d021f7372d79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/truyen-tranh-con-gai')]</value>
      <webElementGuid>432e6581-896a-4885-9019-718985d83ab1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[10]/a</value>
      <webElementGuid>5a83033c-2c2f-45ce-9bb8-19decf4402db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/truyen-tranh-con-gai' and (text() = 'Con gái' or . = 'Con gái')]</value>
      <webElementGuid>a3454a10-2b6d-4ef6-a800-08a896474fea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
