<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Tt c</name>
   <tag></tag>
   <elementGuidId>d4f35612-4e09-4570-9bb3-a30bc6588185</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_mainContent_ctl00_ulStatus > li.active > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='ctl00_mainContent_ctl00_ulStatus']/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>54e92373-3f84-4965-88c4-75e259d5ec86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>?status=-1&amp;sort=</value>
      <webElementGuid>f3e814e5-51ee-4e0d-8ef5-ebec5da0cc28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tất cả</value>
      <webElementGuid>2f60f09a-1c97-45db-9dd3-46a2acd58e65</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_mainContent_ctl00_ulStatus&quot;)/li[@class=&quot;active&quot;]/a[1]</value>
      <webElementGuid>da5c8697-cd86-43b6-b20e-9796bdb1f178</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ctl00_mainContent_ctl00_ulStatus']/li/a</value>
      <webElementGuid>f4f65916-711d-4ce0-b4f6-390af2383616</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Tất cả')]</value>
      <webElementGuid>fbf335c9-427d-44d1-a199-9b926f1e2a67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Truyện Tranh Ngôn Tình Hay Nhất - Truyện Tranh Ngôn Tình Tổng Tài Hot | NetTruyen'])[2]/following::a[1]</value>
      <webElementGuid>6a365711-5fca-4bd1-ad00-f158afae9e29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Thể loại'])[2]/following::a[1]</value>
      <webElementGuid>5d2331fe-c3d8-4872-9582-1b47257a88ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hoàn thành'])[1]/preceding::a[1]</value>
      <webElementGuid>b928f789-8217-4a57-ac17-73f5fffa7497</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đang tiến hành'])[1]/preceding::a[2]</value>
      <webElementGuid>bd9ad00e-23f1-4308-9b4d-64b7a2292e27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '?status=-1&amp;sort=')]</value>
      <webElementGuid>c6fe3761-f79d-48c0-b139-ad08a89bb136</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/ul/li/a</value>
      <webElementGuid>aeec7981-0e6b-4058-acd1-a0e5568f4b4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '?status=-1&amp;sort=' and (text() = 'Tất cả' or . = 'Tất cả')]</value>
      <webElementGuid>335b1f39-92ff-4b3c-bea8-8772b5f26c94</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
