<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_X</name>
   <tag></tag>
   <elementGuidId>dc832709-0af4-4144-ae82-01754160bb1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.wapclosebtn.ads-banner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@onclick=&quot;jQuery('.wap_bottombanner').fadeOut();&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>96486f2f-c0ed-4b70-8337-c3c9b3164b17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wapclosebtn ads-banner</value>
      <webElementGuid>e184521e-9ae7-4b27-8abd-1c93554eb8b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:;</value>
      <webElementGuid>4d78cfdc-6b51-418b-a09c-370eff734b45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>jQuery('.wap_bottombanner').fadeOut();</value>
      <webElementGuid>680a22ba-4267-4573-b1c3-5106001bfdee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>X</value>
      <webElementGuid>0f1ee008-3c6b-4e37-97d1-8c3c82493295</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;aspnetForm&quot;)/main[@class=&quot;main&quot;]/div[@class=&quot;ads-banner wap_bottombanner banner-desktop&quot;]/div[@class=&quot;wap_bottombanner_content&quot;]/div[@class=&quot;textwidget text-center&quot;]/div[@class=&quot;text-center&quot;]/a[@class=&quot;wapclosebtn ads-banner&quot;]</value>
      <webElementGuid>bc88d8a1-ef89-450e-ac09-dad63faaf0e9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@onclick=&quot;jQuery('.wap_bottombanner').fadeOut();&quot;]</value>
      <webElementGuid>811698d8-8976-441f-b894-f8b31dbd4c69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='aspnetForm']/main/div[2]/div/div/div/a</value>
      <webElementGuid>9aebae6b-9610-4f28-be39-bf95c0e44c5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'X')])[2]</value>
      <webElementGuid>8113e9f7-57c4-442f-89fd-e36abc6a0fd9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='nettruyenrr.com'])[1]/following::a[13]</value>
      <webElementGuid>63925e85-1e1e-476a-860b-5e849af302df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Con trai'])[1]/following::a[13]</value>
      <webElementGuid>a980a696-ab1f-47be-885b-bdc19291f5bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='X'])[2]/preceding::a[5]</value>
      <webElementGuid>6f42eb85-b087-4279-8a6c-4e730947b339</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='X'])[3]/preceding::a[14]</value>
      <webElementGuid>3873ffa3-a5c7-4cba-9454-641943ed2bba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='X']/parent::*</value>
      <webElementGuid>6d3c88f5-bf88-491f-b392-71353ea3fc5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:;')]</value>
      <webElementGuid>0450321c-e5ec-48f2-92b5-787863e406c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/a</value>
      <webElementGuid>8e239dcd-52ff-4e79-9b92-40d0e3511a17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'javascript:;' and (text() = 'X' or . = 'X')]</value>
      <webElementGuid>ed8b87b4-371f-439b-9b3f-007524805b9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
