<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_concat(id(, , img-_pop-nettruyenrr-18, _d9c8c2</name>
   <tag></tag>
   <elementGuidId>020d8b8a-4400-42c5-aef8-940d6b3082c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#img-_pop-nettruyenrr-18</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='img-_pop-nettruyenrr-18']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b8651436-13ea-4041-b4ef-0132a5b11682</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ads-banner</value>
      <webElementGuid>19bc9f1b-35fd-4ad3-8abf-a4daefdcf967</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>img-_pop-nettruyenrr-18</value>
      <webElementGuid>e80b59ad-a886-4f27-848d-68ed08642f2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://newoneinoldoneout.pro/popup/banner/Debet_Tai_Tro_NHA_Gif_300x300_08_01_2025_16_52_56.gif</value>
      <webElementGuid>57243da5-f07f-4dbf-b153-567356e2b4a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;img-_pop-nettruyenrr-18&quot;)</value>
      <webElementGuid>2cb1c953-4c2d-49a0-b240-fed69bf931ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='img-_pop-nettruyenrr-18']</value>
      <webElementGuid>bbeff76e-11ea-4b48-a5cd-d307ba864867</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//a[@id='url-_pop-nettruyenrr-18']/img</value>
      <webElementGuid>b3335044-4fd6-426a-9bc0-a4bd634699d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://newoneinoldoneout.pro/popup/banner/Debet_Tai_Tro_NHA_Gif_300x300_08_01_2025_16_52_56.gif')]</value>
      <webElementGuid>da6aaf41-c413-4bec-84af-6e716b5f4ff5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/div/div/div/a/img</value>
      <webElementGuid>4bc84523-de38-4a9d-8a06-f6d10d48a742</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'img-_pop-nettruyenrr-18' and @src = 'https://newoneinoldoneout.pro/popup/banner/Debet_Tai_Tro_NHA_Gif_300x300_08_01_2025_16_52_56.gif']</value>
      <webElementGuid>82d6c6cc-542e-44e8-bbff-f675703e79b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
