<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Cha dch ton b hay vi trang_report__898efe</name>
   <tag></tag>
   <elementGuidId>0056a22d-751e-4dce-bcd3-477da1bd2736</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#report_error_text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='report_error_text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>84860ce1-4df7-4beb-9a4d-320edb6342e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>report_error_text</value>
      <webElementGuid>bb7f58ba-ff44-4b28-b5bd-2536042576cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>796bae24-a3c1-464e-ad93-569077e080a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Mô tả...</value>
      <webElementGuid>f4ad0bcd-ff97-47ac-a290-205a7d3bdecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;report_error_text&quot;)</value>
      <webElementGuid>a5e9f499-31b4-4f9d-ac51-e0a5aead1158</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='report_error_text']</value>
      <webElementGuid>a516f90e-0e7b-4eb6-8cda-fa7a5a2316fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='popup_content']/div/ul/li[2]/textarea</value>
      <webElementGuid>484c3e4f-a1d1-4f50-aabd-19943d8c02b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>90cf0f49-5f73-4cf2-b7a4-0cdb6c6e7a79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'report_error_text' and @placeholder = 'Mô tả...']</value>
      <webElementGuid>812f9808-61e5-42ad-9275-f49bf0732767</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
