<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>scroll</name>
   <tag></tag>
   <elementGuidId>6334b2ab-9854-4d1c-9d0c-ca82ca56f037</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a[title=&quot;Truyện tranh Ta Trời Sinh Đã Là Nhân Vật Phản Diện&quot;] > img.lazy.image-thumb</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ctl00_divCenter']/div/div/div/div[2]/div[7]/figure/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7daf4efd-71ca-4751-a226-02d76eb04c13</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://cdn1.cloud-zzz.com/nettruyen/thumb/ta-troi-sinh-da-la-nhan-vat-phan-dien.jpg</value>
      <webElementGuid>11032c0b-4c25-4146-ac12-e060677bc241</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onerror</name>
      <type>Main</type>
      <value>handleImageError(this);</value>
      <webElementGuid>17fcfce0-6845-4330-bd74-4db4d0f668e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-retries</name>
      <type>Main</type>
      <value>https://cdn1.cloud-ccc.com/nettruyen/thumb/ta-troi-sinh-da-la-nhan-vat-phan-dien.jpg</value>
      <webElementGuid>15dee6bc-b273-4f41-a881-920218ff857e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>lazy image-thumb</value>
      <webElementGuid>0ce5897d-e142-4032-a145-f8060bfce1ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-original</name>
      <type>Main</type>
      <value>https://cdn1.cloud-zzz.com/nettruyen/thumb/ta-troi-sinh-da-la-nhan-vat-phan-dien.jpg</value>
      <webElementGuid>1a7013c7-4139-4c0e-ad95-c778c0723159</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Truyện tranh Ta Trời Sinh Đã Là Nhân Vật Phản Diện</value>
      <webElementGuid>1addf49f-4a68-4d92-bfef-552a008fb104</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>referrerpolicy</name>
      <type>Main</type>
      <value>origin</value>
      <webElementGuid>51480d43-0926-4787-a364-4296c9bdc303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_divCenter&quot;)/div[@class=&quot;Module Module-163&quot;]/div[@class=&quot;ModuleContent&quot;]/div[@class=&quot;items&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;item&quot;]/figure[@class=&quot;clearfix&quot;]/div[@class=&quot;image&quot;]/a[1]/img[@class=&quot;lazy image-thumb&quot;]</value>
      <webElementGuid>c6ec17e7-fdc9-4605-b356-0956d247983f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_divCenter']/div/div/div/div[2]/div[7]/figure/div/a/img</value>
      <webElementGuid>e37ac769-d446-47c2-ad41-b6eb0c2ce8ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Truyện tranh Ta Trời Sinh Đã Là Nhân Vật Phản Diện']</value>
      <webElementGuid>f8af2572-3c5f-4c89-939c-992ef34a6ace</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[7]/figure/div/a/img</value>
      <webElementGuid>b85ffc13-f496-4c12-a797-57587f1c3933</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://cdn1.cloud-zzz.com/nettruyen/thumb/ta-troi-sinh-da-la-nhan-vat-phan-dien.jpg' and @alt = 'Truyện tranh Ta Trời Sinh Đã Là Nhân Vật Phản Diện']</value>
      <webElementGuid>9d0930f2-a223-46e8-9b66-3cc3076a386b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
