<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__1_2</name>
   <tag></tag>
   <elementGuidId>82d53705-1665-4945-9504-82150aa98150</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#close-_pop-nettruyenrr-23</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='close-_pop-nettruyenrr-23']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>8ed23223-b600-4bd4-9862-d505ab46299e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ads-banner</value>
      <webElementGuid>23fbab4f-9536-4932-94af-03904188a3e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>close-_pop-nettruyenrr-23</value>
      <webElementGuid>b42018f7-d3bd-471b-bd52-ef43df097d6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×</value>
      <webElementGuid>99e30fbb-14de-411c-ad26-2148b72de0dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;close-_pop-nettruyenrr-23&quot;)</value>
      <webElementGuid>5f1d91ef-3a19-441a-a409-2b47b25a8662</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='close-_pop-nettruyenrr-23']</value>
      <webElementGuid>37121075-b5e3-4aea-9f29-4fc2ef19f606</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_pop-nettruyenrr-23']/div/div/div/div</value>
      <webElementGuid>3146b59a-51fd-4d9b-9fe6-2869b53b1e05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[4]/following::div[5]</value>
      <webElementGuid>91e2676a-18d3-488c-9eee-ceac52e33c11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[3]/following::div[10]</value>
      <webElementGuid>9acbbb46-5e7d-491c-bea8-d25fed598f66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div</value>
      <webElementGuid>5aac814f-aec5-4609-941b-fabbbd481f38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'close-_pop-nettruyenrr-23' and (text() = '×' or . = '×')]</value>
      <webElementGuid>be627094-38cb-480b-aba6-ab08f835f527</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
