<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Theo di</name>
   <tag></tag>
   <elementGuidId>4ac9ac2c-7014-44d0-ae30-5f66e7155979</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/form/main/div[6]/div/div/div/div[1]/div[2]/div[4]/a[7]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.follow-url.btn.btn-danger.unFollow</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>403b7aef-e104-4185-999b-e7b76143c2f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>follow-url btn btn-danger unFollow</value>
      <webElementGuid>825abb55-cb18-46e2-a365-a2a014bf43bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-id</name>
      <type>Main</type>
      <value>11951</value>
      <webElementGuid>39f54f94-57b7-4e57-8174-7346066c8a2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-status</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>617c5989-7d01-4654-bc95-3db6792088da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Theo dõi </value>
      <webElementGuid>7e51f5f6-db42-4f3c-a45d-4dbc1f593ac2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chapterNav&quot;)/a[@class=&quot;follow-url btn btn-danger unFollow&quot;]</value>
      <webElementGuid>2935eb11-26c2-4ae9-8b30-aad0de77206d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='chapterNav']/a[7]</value>
      <webElementGuid>c28c807d-b57b-46bc-8c34-d10050f09e24</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bỏ theo dõi'])[1]/following::a[1]</value>
      <webElementGuid>f473e665-0a79-4adf-8c5e-f2ec5bc5f4b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sử dụng mũi tên trái (←) hoặc phải (→) để chuyển chapter'])[1]/following::a[7]</value>
      <webElementGuid>59df151f-8db4-4a54-b867-be9298468c85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chap trước'])[1]/preceding::a[25]</value>
      <webElementGuid>46513d33-9a84-4985-b559-c3b70f369e17</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/a[7]</value>
      <webElementGuid>ff424030-5b73-49c3-8690-44c5337e85ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = '  Theo dõi ' or . = '  Theo dõi ')]</value>
      <webElementGuid>504a89e0-ced3-4809-8e21-a219d27304e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
