<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_2</name>
   <tag></tag>
   <elementGuidId>86750484-a2f0-4e18-895f-275717a6c0a5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ctl00_mainContent_ctl01_divPager']/ul/li[3]/a</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.page-link</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cac1fc02-b745-44bc-8862-55e154a7c34a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>page-link</value>
      <webElementGuid>23eb2f8f-f870-488a-af09-ddccf8f4fef9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://nettruyenrr.com/tim-truyen/manhwa-11400?page=2</value>
      <webElementGuid>c71666d3-5a6b-4e02-a199-227a2aaed139</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>defcaac8-4f41-4d4c-9a43-ea7588d8f4d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_mainContent_ctl01_divPager&quot;)/ul[@class=&quot;pagination&quot;]/li[@class=&quot;page-item&quot;]/a[@class=&quot;page-link&quot;]</value>
      <webElementGuid>8fddfb02-9011-424b-8828-28fd88494eee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_mainContent_ctl01_divPager']/ul/li[3]/a</value>
      <webElementGuid>74f85c77-9f43-4901-a82e-c2316e39c11e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>(//a[contains(text(),'2')])[28]</value>
      <webElementGuid>b5701845-6285-48d8-becf-c15590d21a8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ngày cập nhật:'])[36]/following::a[1]</value>
      <webElementGuid>5031b7b0-3170-4215-967f-3d6a9a16faef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Theo dõi:'])[36]/following::a[1]</value>
      <webElementGuid>dbb9e67a-a2e9-4c50-8391-77c7e4c9512c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='...'])[1]/preceding::a[7]</value>
      <webElementGuid>a2d58df1-3b1a-471b-8ff2-f7e7c329a98b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='›'])[1]/preceding::a[9]</value>
      <webElementGuid>f57c96da-0b10-42eb-a31c-e492b508ddde</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://nettruyenrr.com/tim-truyen/manhwa-11400?page=2')]</value>
      <webElementGuid>3807efdb-0186-4d94-971b-b461d137f99a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/ul/li[3]/a</value>
      <webElementGuid>838cf16e-6789-4f76-be09-eb7a9de4a43e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://nettruyenrr.com/tim-truyen/manhwa-11400?page=2' and (text() = '2' or . = '2')]</value>
      <webElementGuid>6aaefa18-5838-433f-9103-db4f85937ca0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
