<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_</name>
   <tag></tag>
   <elementGuidId>8d17f297-a87f-41f1-bb81-5b37b8995530</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='close-_pop-nettruyenrr-18']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#close-_pop-nettruyenrr-18</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>39a0c1aa-6834-4d7a-9510-99635dbcf87a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ads-banner</value>
      <webElementGuid>490607a6-fd2f-4d7d-b675-e9dd2b90f15a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>close-_pop-nettruyenrr-18</value>
      <webElementGuid>49424ec1-566c-4bd9-a699-3c9c53342e76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×</value>
      <webElementGuid>8421a7dd-2097-4d8c-8ef8-d09196b9b885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;close-_pop-nettruyenrr-18&quot;)</value>
      <webElementGuid>407702d7-428a-41dc-a583-9dd82d135a82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='close-_pop-nettruyenrr-18']</value>
      <webElementGuid>0533d6f4-c648-4330-aba3-d711813a0cee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_pop-nettruyenrr-18']/div/div/div/div</value>
      <webElementGuid>9068cb0c-6ec3-42b2-93ad-38302821c17b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đăng ký'])[2]/following::div[5]</value>
      <webElementGuid>56c36e7c-672b-479c-bcb8-a021961582f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[3]/preceding::div[1]</value>
      <webElementGuid>c147f86c-5732-46cf-85d2-b37c5a448913</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[4]/preceding::div[6]</value>
      <webElementGuid>53da04c1-1c46-4145-8cb8-4135bdb51e56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/div/div/div/div/div</value>
      <webElementGuid>070d73bf-bba2-4853-a2b4-cd22b16647a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'close-_pop-nettruyenrr-18' and (text() = '×' or . = '×')]</value>
      <webElementGuid>ca39650f-1bb7-4ff4-88ef-21e1d2f96bb2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
