<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ang tin hnh_1</name>
   <tag></tag>
   <elementGuidId>80e47a2e-1cca-4fd4-a539-b6eeeb94ebe6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ctl00_mainContent_ctl00_ulStatus > li:nth-of-type(3) > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='ctl00_mainContent_ctl00_ulStatus']/li[3]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0fcb234f-118f-4af0-9b1e-d16af4a9b05b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>?status=1&amp;sort=19</value>
      <webElementGuid>0e0fa215-7acf-4a52-96a7-85ec4e036ccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Đang tiến hành</value>
      <webElementGuid>07976f82-4d49-402e-9230-8e450addd932</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_mainContent_ctl00_ulStatus&quot;)/li[3]/a[1]</value>
      <webElementGuid>949638e5-114e-4a2e-83e0-b77be6085c02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ctl00_mainContent_ctl00_ulStatus']/li[3]/a</value>
      <webElementGuid>20ceeea1-ff96-4a3e-aa28-92ddf6ec2cba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Đang tiến hành')]</value>
      <webElementGuid>b6795b78-3c0a-4cbc-83a9-c87a077f0867</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hoàn thành'])[1]/following::a[1]</value>
      <webElementGuid>67dcee9a-938a-4465-a7c4-2bae3dd4a40f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tất cả'])[3]/following::a[2]</value>
      <webElementGuid>29dc6c1b-744c-49db-a76e-d3cb69b8b0a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sắp xếp theo:'])[1]/preceding::a[1]</value>
      <webElementGuid>ee84a0ee-ae72-468b-a52e-7c931bb66dd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Đang tiến hành']/parent::*</value>
      <webElementGuid>97d5bffd-3c5a-4a8b-b33b-1a881c472abb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '?status=1&amp;sort=19')]</value>
      <webElementGuid>08dadb2a-643f-44f9-868c-6f139033ddeb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/ul/li[3]/a</value>
      <webElementGuid>d62d5738-6706-422a-beaf-9ee55376a79f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '?status=1&amp;sort=19' and (text() = 'Đang tiến hành' or . = 'Đang tiến hành')]</value>
      <webElementGuid>095f2c8c-e867-486d-8507-ab2cd6a4736e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
