<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Top Follow_1</name>
   <tag></tag>
   <elementGuidId>894f6336-3d7b-435f-8165-dbfa6b36db8b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a:nth-of-type(10)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ctl00_mainContent_ctl00_divSort']/div[2]/div/a[10]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1586fbc7-7914-470a-b77d-d3b8e14bc365</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rel</name>
      <type>Main</type>
      <value>nofollow</value>
      <webElementGuid>46160d84-c179-4316-a64e-8e7b2c188aac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value> ?status=2&amp;sort=19</value>
      <webElementGuid>451c4ae3-2457-428b-a57c-5d9c7bea9fb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>  Top Follow</value>
      <webElementGuid>2ab6b93f-7490-42bd-8e84-159dfc5055da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ctl00_mainContent_ctl00_divSort&quot;)/div[@class=&quot;col-sm-9&quot;]/div[@class=&quot;hidden-xs&quot;]/a[10]</value>
      <webElementGuid>618f1947-3a74-40ed-b1a9-540028cad9d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ctl00_mainContent_ctl00_divSort']/div[2]/div/a[10]</value>
      <webElementGuid>f075a9c9-c2f4-43c8-83f4-47b8573ee32e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Doremon'])[1]/preceding::a[2]</value>
      <webElementGuid>3542075f-2171-4a3e-8843-8bb8836fdf15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chapter 823'])[1]/preceding::a[3]</value>
      <webElementGuid>eb5360d9-3bcb-46e9-b874-33fe549aa1f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Top Follow']/parent::*</value>
      <webElementGuid>1a0dfa51-6a42-4647-8e6c-b938b5c89005</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, ' ?status=2&amp;sort=19')]</value>
      <webElementGuid>ea8b76a2-9ab1-4a95-87fb-e4047e235ff0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[10]</value>
      <webElementGuid>c50799a9-c507-4fc4-be20-88bbc2bc2373</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = ' ?status=2&amp;sort=19' and (text() = '  Top Follow' or . = '  Top Follow')]</value>
      <webElementGuid>87ae115e-cd62-4c85-9610-4a744d10414d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
