<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div__1_2_3</name>
   <tag></tag>
   <elementGuidId>88fd7e7f-99da-4c64-8096-4131ef45570d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#close-_pop-nettruyenrr-23</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='close-_pop-nettruyenrr-23']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>9dd216e6-48ed-4861-8868-de8862af7ae2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ads-banner</value>
      <webElementGuid>e56c3210-7229-47ba-a656-7639c089ab5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>close-_pop-nettruyenrr-23</value>
      <webElementGuid>15ff3b88-459a-4468-99f9-67a60f4ac220</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×</value>
      <webElementGuid>0f91cc4a-3db5-4d3c-b9d2-7e502aab82a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;close-_pop-nettruyenrr-23&quot;)</value>
      <webElementGuid>582bd6aa-0316-4164-bafc-659e53c45933</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='close-_pop-nettruyenrr-23']</value>
      <webElementGuid>b800983d-b6af-413e-a7a2-72cca4818fbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='_pop-nettruyenrr-23']/div/div/div/div</value>
      <webElementGuid>1d98caff-a8e3-4e6d-8d70-be6d0d2a4b77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[4]/following::div[5]</value>
      <webElementGuid>ce15b464-490b-4973-a7d9-28cbd5c8e546</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='×'])[3]/following::div[10]</value>
      <webElementGuid>9641258d-50fc-4c58-955c-14e184fffa74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/div/div</value>
      <webElementGuid>a95153e2-bed2-4a80-8bcf-248c01fe7dec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'close-_pop-nettruyenrr-23' and (text() = '×' or . = '×')]</value>
      <webElementGuid>dc40398f-8c6b-4aec-9aee-683f6858d33e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
